# Place this file into config folder of your RailsRoot
api-key: '188a8b68-f962-4843-b2ee-bc3a0846e3bc'
development:
 enabled: false
production:
  enabled: true
staging:
  api-key: '188a8b68-f962-4843-b2ee-bc3a0846e3bc' # You can change if you have create different project
  enabled: true
